spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/workspace/h2_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true -> system.out 으로 찍히기 때문에 운영환경에서 사용 안함. 운영환경에서는 log로 찍어야함.
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace